Repository stack-spot/stackspot-intellij-extension, pull requests merged in 2022-09, with the labels that each got.

#18 Bugfix/stack url dialog
  src/main/kotlin/com/stackspot/intellij/actions/ImportStackAction.kt
  src/main/kotlin/com/stackspot/intellij/commons/UrlDialogExtension.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotNoStackfilesErrorPanel.kt
Labels: bug, ready-for-review

#20 fix: added validation if stack file exists inside stack
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotNoStackfilesErrorPanel.kt
  src/main/kotlin/com/stackspot/model/ImportedStacks.kt
Labels: bug, ready-for-review

#19 Feature: Improve plugin description in marketplace page
  src/main/resources/META-INF/plugin.xml
Labels: enhancement, ready-for-review

#22 changes: changed the documentation url inside the readme
  README.md
Labels: enhancement, changes, ready-for-review

#23 Feature: Created workflow to generate release notes and publish plugin
  .github/release.yaml
  .github/workflows/check-callback.yml
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
  build.gradle.kts
Labels: enhancement, ready-for-review

#24 Refactor: Change reusable workflows to use the main branch instead of release branch
  .github/workflows/check-callback.yml
  .github/workflows/publish-release.yml
Labels: changes, ready-for-review

#26 Bug Fix: Changed workflows for each event type and corrected the workflow for plugin publishing
  .github/workflows/check-callback.yml
  .github/workflows/prereleased.yml
  .github/workflows/publish-marketplace.yml
  .github/workflows/released.yml
  .github/workflows/security.yml
Labels: bug, ready-for-review

#27 Bug Fix: Changed workflows for plugin publishing
  .github/workflows/check-callback.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/prereleased.yml
  .github/workflows/publish-marketplace.yml
  .github/workflows/released.yml
  .github/workflows/security.yml
Labels: bug, ready-for-review

#28 Bug Fix: Moved changelog jobs into deploy prod workflow
  .github/workflows/deploy-prod.yml
  .github/workflows/publish-marketplace.yml
Labels: bug, ready-for-review

#29 Bug Fix: Changed changelog extension in build gradle and disable buildSearchableOptions
  CHANGELOG.md
  build.gradle.kts
Labels: bug, ready-for-review

#30 Bug Fix: Added project version property in update changelog command
  .github/workflows/deploy-prod.yml
Labels: bug, ready-for-review

#33 Feature: Add Sonarqube and first unit tests
  .github/workflows/deploy-prod.yml
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/model/Stack.kt
  src/main/kotlin/com/stackspot/model/Stackfile.kt
  src/test/kotlin/com/stackspot/empty.json
  src/test/kotlin/com/stackspot/services/CreateProjectServiceTest.kt
Labels: enhancement, ready-for-review

#34 Changelog update - `v0.1.4`
  CHANGELOG.md
Labels: ignore-for-release

#40 Release 0.1.4
  .github/workflows/deploy-prod.yml
  CHANGELOG.md
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/model/Stack.kt
  src/main/kotlin/com/stackspot/model/Stackfile.kt
  src/test/kotlin/com/stackspot/services/CreateProjectServiceTest.kt
Labels: ready-for-review, ignore-for-release
