Repository stack-spot/stackspot-intellij-extension, pull requests merged in 2022-10, with the labels that each got.

#48 Feature: Improve code coverage with unit tests
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/stackspot/constants/Constants.kt
  src/main/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunner.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitBranch.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitConfig.kt
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/intellij/services/GetDocumentationService.kt
  src/main/kotlin/com/stackspot/intellij/services/enums/RepositoryUriGenerator.kt
  src/main/kotlin/com/stackspot/intellij/ui/StackSpotTerminalRunner.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotGitConfigErrorPanel.kt
  src/main/kotlin/com/stackspot/intellij/ui/toolwindow/StackSpotToolWindow.kt
  src/main/kotlin/com/stackspot/model/Stack.kt
  src/main/kotlin/com/stackspot/yaml/YamlExtensions.kt
  src/main/kotlin/com/stackspot/yaml/YamlNotFoundError.kt
  src/test/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunnerTest.kt
  src/test/kotlin/com/stackspot/intellij/commons/UrlDialogExtensionTest.kt
  src/test/kotlin/com/stackspot/intellij/services/CreateProjectServiceTest.kt
  src/test/kotlin/com/stackspot/intellij/services/GetDocumentationServiceTest.kt
  src/test/kotlin/com/stackspot/intellij/services/enums/ProjectWizardStateTest.kt
  src/test/kotlin/com/stackspot/intellij/services/enums/RepositoryUriGeneratorTest.kt
  src/test/kotlin/com/stackspot/model/empty.json
  src/test/kotlin/com/stackspot/services/CreateProjectServiceTest.kt
  src/test/kotlin/com/stackspot/yaml/empty.json
  src/test/resources/junit-platform.properties
  src/test/resources/yaml/plugins/empty.json
  src/test/resources/yaml/stackfiles/empty.json
  src/test/resources/yaml/stacks/default-stack/stack.yaml
  src/test/resources/yaml/stacks/default-stack/use-case.md
  src/test/resources/yaml/stacks/empty.json
  src/test/resources/yaml/templates/empty.json
Labels: enhancement, ready-for-review

#54 Changelog update - `v1.0.0`
  CHANGELOG.md
Labels: ignore-for-release

#55 Release 1.0.0
  CHANGELOG.md
  build.gradle.kts
  gradle.properties
  src/main/kotlin/com/stackspot/constants/Constants.kt
  src/main/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunner.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitBranch.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitConfig.kt
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/intellij/services/GetDocumentationService.kt
  src/main/kotlin/com/stackspot/intellij/services/enums/RepositoryUriGenerator.kt
  src/main/kotlin/com/stackspot/intellij/ui/StackSpotTerminalRunner.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotGitConfigErrorPanel.kt
  src/main/kotlin/com/stackspot/intellij/ui/toolwindow/StackSpotToolWindow.kt
  src/main/kotlin/com/stackspot/model/Stack.kt
  src/main/kotlin/com/stackspot/yaml/YamlExtensions.kt
  src/main/kotlin/com/stackspot/yaml/YamlNotFoundError.kt
  src/test/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunnerTest.kt
  src/test/kotlin/com/stackspot/intellij/commons/UrlDialogExtensionTest.kt
  src/test/kotlin/com/stackspot/intellij/services/CreateProjectServiceTest.kt
  src/test/kotlin/com/stackspot/intellij/services/GetDocumentationServiceTest.kt
  src/test/kotlin/com/stackspot/intellij/services/enums/ProjectWizardStateTest.kt
  src/test/kotlin/com/stackspot/intellij/services/enums/RepositoryUriGeneratorTest.kt
  src/test/kotlin/com/stackspot/model/empty.json
  src/test/kotlin/com/stackspot/services/CreateProjectServiceTest.kt
  src/test/kotlin/com/stackspot/yaml/empty.json
  src/test/resources/junit-platform.properties
  src/test/resources/yaml/plugins/empty.json
  src/test/resources/yaml/stackfiles/empty.json
  src/test/resources/yaml/stacks/default-stack/stack.yaml
  src/test/resources/yaml/stacks/default-stack/use-case.md
  src/test/resources/yaml/stacks/empty.json
  src/test/resources/yaml/templates/empty.json
Labels: ready-for-review, ignore-for-release

#61 Feature: Removed mandatory template in stackfile
  src/main/kotlin/com/stackspot/intellij/services/StackSpotToolWindowService.kt
  src/main/kotlin/com/stackspot/model/Stackfile.kt
Labels: enhancement, ready-for-review

#60 Bug Fix: Documentation link in project wizard was not visible
  src/main/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunner.kt
  src/main/kotlin/com/stackspot/intellij/commands/BaseCommand.kt
  src/main/kotlin/com/stackspot/intellij/commands/Command.kt
  src/main/kotlin/com/stackspot/intellij/commands/CommandRunner.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitBranch.kt
  src/main/kotlin/com/stackspot/intellij/commands/git/GitConfig.kt
  src/main/kotlin/com/stackspot/intellij/commands/stk/CommandInfoList.kt
  src/main/kotlin/com/stackspot/intellij/commands/stk/CreateProjectByStackfile.kt
  src/main/kotlin/com/stackspot/intellij/commands/stk/DeleteStack.kt
  src/main/kotlin/com/stackspot/intellij/commands/stk/UpdateAllStacks.kt
  src/main/kotlin/com/stackspot/intellij/commands/stk/UpdateStack.kt
  src/main/kotlin/com/stackspot/intellij/commons/ThreadExecutor.kt
  src/main/kotlin/com/stackspot/intellij/listeners/TerminalToolWindowRegisteredListener.kt
  src/main/kotlin/com/stackspot/intellij/services/CreateProjectService.kt
  src/main/kotlin/com/stackspot/intellij/services/GetDocumentationService.kt
  src/main/kotlin/com/stackspot/intellij/ui/StackSpotTerminalRunner.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotNoStackfilesErrorPanel.kt
  src/test/kotlin/com/stackspot/intellij/commands/BackgroundCommandRunnerTest.kt
Labels: bug, ready-for-review

#63 Bug Fix: Compatibility error in plugin check fixed
  src/main/kotlin/com/stackspot/intellij/services/GetDocumentationService.kt
  src/main/kotlin/com/stackspot/intellij/ui/toolwindow/panels/Component.kt
  src/main/kotlin/com/stackspot/intellij/ui/toolwindow/panels/PluginInputsPanel.kt
  src/main/kotlin/com/stackspot/intellij/ui/toolwindow/panels/ValidationHandler.kt
  src/main/kotlin/com/stackspot/model/Input.kt
Labels: bug, ready-for-review

#67 fix: returning the template requirements check
  src/main/kotlin/com/stackspot/intellij/services/StackSpotToolWindowService.kt
Labels: ready-for-review, ignore-for-release
