Repository stack-spot/stackspot-intellij-extension, pull requests merged in 2022-08, with the labels that each got.

#7 feature: created workflows for integration with another repository
  .github/workflows/check-callback.yml
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/security-pipeline.yml
Labels: enhancement

#6 fix: removed use of internal api
  build.gradle.kts
  src/main/kotlin/com/stackspot/intellij/listeners/TerminalToolWindowRegisteredListener.kt
  src/main/kotlin/com/stackspot/intellij/ui/project_wizard/panels/StackSpotSuccessPanel.kt
  src/main/resources/META-INF/plugin.xml
Labels: bug

#13 Feature: Improve GHA workflow
  .github/workflows/check-callback.yml
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/header-license-check.yml
  .github/workflows/security-pipeline.yml
Labels: enhancement, changes

#14 fix: changed statuses href
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
Labels: enhancement, changes

#15 Changes/workflows
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
Labels: enhancement, ready-for-review

#16 Changes/workflows
  .github/workflows/deploy-pre-release.yml
  .github/workflows/deploy-prod.yml
Labels: bug, ready-for-review

#17 BugFix: Project wizard always stuck in "no stackfiles panel"
  src/main/kotlin/com/stackspot/constants/Constants.kt
  src/main/kotlin/com/stackspot/model/ImportedStacks.kt
Labels: bug, ready-for-review
